translations = {
    "de": {
        "app_title": "🎫 Revolution Ticket-System",
        "app_choose": "Wähle links: Kunden, Warteraum oder Sachbearbeiter.",

        "pull_title": "🎫 Nummer ziehen",
        "pull_info": "Bitte drücken Sie auf den Button, um Ihre Wartenummer zu erhalten.",
        "pull_button": "Nummer ziehen",
        "pull_wait": "Bitte warten Sie, bis Ihre Nummer aufgerufen wird.",
        "your_number": "Ihre Nummer",

        "waiting_room": "📢 Warteraum",
        "current_ticket": "Aktuelles Ticket",
        "queue_position": "Ihre Position in der Warteschlange:",
        "almost_called": "🎉 Sie sind gleich dran oder werden bereits aufgerufen!",
        "waiting_numbers": "Wartende Nummern",
        "no_more_tickets": "Keine weiteren Tickets.",
        "called_now": "🎉 Ihre Nummer wird jetzt aufgerufen!",

        "login_title": "🔐 Sachbearbeiter Login",
        "username": "Benutzername",
        "password": "Passwort",
        "login": "Login",
        "login_error": "Falscher Benutzername oder Passwort",
        "logout": "Logout",

        "agent_title": "🧑‍💼 Sachbearbeiter",
        "waiting_tickets": "Wartende Tickets",
        "no_waiting": "Keine wartenden Tickets.",
        "call_next": "Nächstes Ticket aufrufen",
        "in_progress": "Aktuell in Bearbeitung",
        "none_in_progress": "Kein Ticket in Bearbeitung.",
        "finish": "Fertig",
        "finished": "Ticket abgeschlossen.",
        "no_description": "Keine Beschreibung angegeben",
        "no_ticket_called": "Noch kein Ticket aufgerufen.",
        "ticket_called": "Ticket aufgerufen:",
        "ticket_finished": "Ticket abgeschlossen:",
        "no_ticket_in_progress": "Kein Ticket in Bearbeitung.",
        "call_next": "➡️ Nächstes Ticket aufrufen",
        "finish_ticket": "✔️ Ticket abschließen",
        "description": "Kurzbeschreibung",
        "about_title": "Revolution Ticket-System",
        "about_sub": "Willkommen! Hier erfahren Sie, wer wir sind und was unser System besonders macht.",

        "about_us_title": "Über uns",
        "about_us_text": "Wir entwickeln moderne, digitale Lösungen für Warte- und Ticketsysteme. Unser Ziel ist es, Abläufe zu vereinfachen, Wartezeiten transparent zu machen und sowohl Kunden als auch Mitarbeitern ein angenehmes, effizientes Erlebnis zu bieten.",

        "mission_title": "Unsere Mission",
        "mission_text": "Wir glauben an klare Prozesse, intuitive Bedienung und moderne Technologie. Das Revolution Ticket-System wurde entwickelt, um Organisationen jeder Größe eine einfache, zuverlässige und flexible Lösung zu bieten.",

        "why_title": "Warum unser System?",
        "why_1": "✔ Intuitive Bedienung für Kunden und Mitarbeiter",
        "why_2": "✔ Klare Struktur und moderne Benutzeroberfläche",
        "why_3": "✔ Mehrsprachige Unterstützung",
        "why_4": "✔ Echtzeit-Informationen über Wartezeiten",
        "why_5": "✔ Flexibel anpassbar für jede Branche",

        "contact_title": "Kontakt",
        "contact_mail": "📧 E-Mail: support@revolution-ticketsystem.com",
        "contact_phone": "📞 Telefon: +49 123 456 789",
        "contact_location": "📍 Standort: Hessen, Deutschland",
        "description_title": "Kurzbeschreibung (optional)",
        "description_placeholder": "Bitte geben Sie kurz Ihr Anliegen ein (optional)…",
        "no_tickets_left": "Keine Tickets mehr vorhanden.",
        "login_success": "Erfolgreich eingeloggt!",
        "ticket_word": "Ticket",
        "finished_word": "abgeschlossen.",

    },

    "en": {
        "app_title": "🎫 Revolution Ticket System",
        "app_choose": "Choose on the left: Customers, Waiting Room or Agent.",

        "pull_title": "🎫 Pull a Number",
        "pull_info": "Please press the button to receive your waiting number.",
        "pull_button": "Pull Number",
        "pull_wait": "Please wait until your number is called.",
        "your_number": "Your Number",

        "waiting_room": "📢 Waiting Room",
        "current_ticket": "Current Ticket",
        "queue_position": "Your position in the queue:",
        "almost_called": "🎉 You are next or already being called!",
        "waiting_numbers": "Waiting Numbers",
        "no_more_tickets": "No more tickets.",
        "called_now": "🎉 Your number is being called now!",

        "login_title": "🔐 Agent Login",
        "username": "Username",
        "password": "Password",
        "login": "Login",
        "login_error": "Incorrect username or password",
        "logout": "Logout",

        "agent_title": "🧑‍💼 Agent",
        "waiting_tickets": "Waiting Tickets",
        "no_waiting": "No waiting tickets.",
        "call_next": "Call Next Ticket",
        "in_progress": "Currently in Progress",
        "none_in_progress": "No ticket in progress.",
        "finish": "Finish",
        "finished": "Ticket completed.",
        "no_description": "No description provided",
        "no_ticket_called": "No ticket has been called yet.",
        "ticket_called": "Ticket called:",
        "ticket_finished": "Ticket finished:",
        "no_ticket_in_progress": "No ticket in progress.",
        "call_next": "➡️ Call next ticket",
        "finish_ticket": "✔️ Finish ticket",
        "description": "Description",
        "about_title": "Revolution Ticket System",
        "about_sub": "Welcome! Here you can learn who we are and what makes our system special.",

        "about_us_title": "About Us",
        "about_us_text": "We develop modern digital solutions for queue and ticket systems. Our goal is to simplify processes, make waiting times transparent, and provide both customers and staff with an efficient and pleasant experience.",

        "mission_title": "Our Mission",
        "mission_text": "We believe in clear processes, intuitive usability, and modern technology. The Revolution Ticket System was created to offer organizations of all sizes a simple, reliable, and flexible solution.",

        "why_title": "Why Our System?",
        "why_1": "✔ Intuitive for customers and staff",
        "why_2": "✔ Clear structure and modern interface",
        "why_3": "✔ Multilingual support",
        "why_4": "✔ Real-time waiting information",
        "why_5": "✔ Flexible for any industry",

        "contact_title": "Contact",
        "contact_mail": "📧 Email: support@revolution-ticketsystem.com",
        "contact_phone": "📞 Phone: +49 123 456 789",
        "contact_location": "📍 Location: Hesse, Germany",
        "description_title": "Short description (optional)",
        "description_placeholder": "Please briefly describe your request (optional)…",
        "no_tickets_left": "No more tickets available.",
        "login_success": "Successfully logged in!",
        "ticket_word": "Ticket",
        "finished_word": "completed.",

    },

    "fr": {
        "app_title": "🎫 Système de Tickets Révolutionnaire",
        "app_choose": "Choisissez à gauche : Clients, Salle d'attente ou Agent.",

        "pull_title": "🎫 Prendre un numéro",
        "pull_info": "Veuillez appuyer sur le bouton pour recevoir votre numéro d'attente.",
        "pull_button": "Prendre un numéro",
        "pull_wait": "Veuillez attendre que votre numéro soit appelé.",
        "your_number": "Votre numéro",

        "waiting_room": "📢 Salle d'attente",
        "current_ticket": "Ticket actuel",
        "queue_position": "Votre position dans la file :",
        "almost_called": "🎉 Vous êtes le prochain ou déjà appelé !",
        "waiting_numbers": "Numéros en attente",
        "no_more_tickets": "Plus aucun ticket.",
        "called_now": "🎉 Votre numéro est appelé maintenant !",

        "login_title": "🔐 Connexion Agent",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "login": "Connexion",
        "login_error": "Nom d'utilisateur ou mot de passe incorrect",
        "logout": "Déconnexion",

        "agent_title": "🧑‍💼 Agent",
        "waiting_tickets": "Tickets en attente",
        "no_waiting": "Aucun ticket en attente.",
        "call_next": "Appeler le prochain ticket",
        "in_progress": "Actuellement en traitement",
        "none_in_progress": "Aucun ticket en traitement.",
        "finish": "Terminer",
        "finished": "Ticket terminé.",
        "no_description": "Aucune description fournie",
        "no_ticket_called": "Aucun ticket n’a encore été appelé.",
        "ticket_called": "Ticket appelé :",
        "ticket_finished": "Ticket terminé :",
        "no_ticket_in_progress": "Aucun ticket en cours.",
        "call_next": "➡️ Appeler le prochain ticket",
        "finish_ticket": "✔️ Terminer le ticket",
        "description": "Description",
        "about_title": "Système de Tickets Revolution",
        "about_sub": "Bienvenue ! Découvrez qui nous sommes et ce qui rend notre système unique.",

        "about_us_title": "À propos de nous",
        "about_us_text": "Nous développons des solutions numériques modernes pour les systèmes de file d’attente et de tickets. Notre objectif est de simplifier les processus, de rendre les temps d’attente transparents et d’offrir une expérience efficace et agréable aux clients comme aux employés.",

        "mission_title": "Notre mission",
        "mission_text": "Nous croyons en des processus clairs, une utilisation intuitive et une technologie moderne. Le Système de Tickets Revolution a été conçu pour offrir une solution simple, fiable et flexible aux organisations de toute taille.",

        "why_title": "Pourquoi notre système ?",
        "why_1": "✔ Utilisation intuitive pour les clients et les employés",
        "why_2": "✔ Structure claire et interface moderne",
        "why_3": "✔ Support multilingue",
        "why_4": "✔ Informations en temps réel sur les temps d’attente",
        "why_5": "✔ Flexible pour tous les secteurs",

        "contact_title": "Contact",
        "contact_mail": "📧 E-mail : support@revolution-ticketsystem.com",
        "contact_phone": "📞 Téléphone : +49 123 456 789",
        "contact_location": "📍 Localisation : Hesse, Allemagne",
        "description_title": "Brève description (optionnel)",
        "description_placeholder": "Veuillez décrire brièvement votre demande (optionnel)…",
        "no_tickets_left": "Plus de tickets disponibles.",
        "login_success": "Connexion réussie !",
        "ticket_word": "Ticket",
        "finished_word": "terminé.",

    },

    "cn": {
        "app_title": "🎫 革命票务系统",
        "app_choose": "请选择：客户、候诊室或工作人员。",

        "pull_title": "🎫 取号",
        "pull_info": "请按下按钮获取您的排队号码。",
        "pull_button": "取号",
        "pull_wait": "请等待您的号码被叫到。",
        "your_number": "您的号码",

        "waiting_room": "📢 候诊室",
        "current_ticket": "当前号码",
        "queue_position": "您在队列中的位置：",
        "almost_called": "🎉 您马上就要被叫到！",
        "waiting_numbers": "等待中的号码",
        "no_more_tickets": "没有更多号码。",
        "called_now": "🎉 您的号码正在被叫到！",

        "login_title": "🔐 工作人员登录",
        "username": "用户名",
        "password": "密码",
        "login": "登录",
        "login_error": "用户名或密码错误",
        "logout": "退出登录",

        "agent_title": "🧑‍💼 工作人员",
        "waiting_tickets": "等待中的票号",
        "no_waiting": "没有等待中的票号。",
        "call_next": "呼叫下一个号码",
        "in_progress": "正在处理",
        "none_in_progress": "没有正在处理的号码。",
        "finish": "完成",
        "finished": "号码已完成。",
        "no_description": "没有提供描述",
        "no_ticket_called": "尚未叫号。",
        "ticket_called": "已叫号：",
        "ticket_finished": "已完成：",
        "no_ticket_in_progress": "当前没有正在处理的号码。",
        "call_next": "➡️ 呼叫下一个号码",
        "finish_ticket": "✔️ 完成号码",
        "description": "描述",
        "about_title": "Revolution 排队与票务系统",
        "about_sub": "欢迎！在这里您可以了解我们是谁，以及我们的系统有何独特之处。",

        "about_us_title": "关于我们",
        "about_us_text": "我们致力于开发现代化的排队与票务数字解决方案。我们的目标是简化流程，使等待时间透明化，并为客户和员工提供高效、舒适的体验。",

        "mission_title": "我们的使命",
        "mission_text": "我们相信清晰的流程、直观的操作和现代技术。Revolution 票务系统旨在为各种规模的组织提供简单、可靠且灵活的解决方案。",

        "why_title": "为什么选择我们的系统？",
        "why_1": "✔ 客户与员工均可轻松使用",
        "why_2": "✔ 清晰结构与现代界面",
        "why_3": "✔ 多语言支持",
        "why_4": "✔ 实时等待信息",
        "why_5": "✔ 适用于各行业的灵活性",

        "contact_title": "联系方式",
        "contact_mail": "📧 邮箱：support@revolution-ticketsystem.com",
        "contact_phone": "📞 电话：+49 123 456 789",
        "contact_location": "📍 地址：德国黑森州",
        "description_title": "简短说明（可选）",
        "description_placeholder": "请简要描述您的需求（可选）…",
        "no_tickets_left": "没有更多可用的号码。",
        "login_success": "登录成功！",
        "ticket_word": "票号",
        "finished_word": "已完成。",




    }
}
